package com.mha.harrypotter.model.dto;

/**
 * Response from API containing token
 * 
 * @author michel
 * @version 0.0.1
 * 
 */

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@JsonIgnoreProperties(ignoreUnknown = true)
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class UserResponse {
	
	
	@Getter
	@Setter
	private String email;
	@Getter
	@Setter
	private String password;
	@ApiModelProperty(notes = "ID user generated by API")
	@Getter
	@Setter
	private int id;
	@ApiModelProperty(notes = "token needed to access API data")
	@Getter
	@Setter
	private String apiKey;
	@Getter
	@Setter
	private String name;

}
